import type { Metadata } from "next";
import "./globals.css";
import { ContentLayout } from "@/components/layout/content-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContentLayout>
        {children}
      </ContentLayout>
    </html>
  );
}
