name: Develop

on:
  pull_request:
    branches:
     - develop

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - name: Install dependencies
       run: npm i

     - name: Build application
       run: npm run build

  AcceptRefusePR:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Approving PR if the build passes
        id: approved
        uses: juliangruber/approve-pull-request-action@v2
        with: 
          github-token: ${{ secrets.ADM_TOKEN }}
          number: ${{ github.event.pull_request.number }}
      
      - name: Merge PR
        if: steps.approved.outcome == 'success'
        uses: juliangruber/merge-pull-request-action@v1
        with: 
          github-token: ${{ secrets.ADM_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
      
      - run: echo "HEAD:${{github.event.pull_request.head.repo.name}}, BASE:${{github.event.pull_request.base.repo.name}}"